pipeline{
    agent any
    stages{
        stage("Clean Up"){
            steps{
                dotnetClean()
                deleteDir()
            }
        }
        stage("Build"){
            steps{
                dir("WcCmdLineTool"){
                    dotnetBuild()
                }
            }
        }
        stage("Test"){
            steps{
                dir("WcCmdLineTool"){
                    dotnetTest()
                }
            }
        }
    }
}
